project: rl-intraday
seed: 42

data:
  instrument: SPY
  minute_file: data/raw/spy_1min.parquet        # Polygon data for SPY
  vix_file: data/external/vix.csv
  cvol_file: data/external/cvol.csv
  macro_flags_file: data/external/macro_flags.csv
  session:
    tz: America/New_York
    rth_start: "09:30"
    rth_end: "16:00"
  lookback_bars: 120            # ~2 hours context for LSTM
  resample: "1min"
  drop_na_policy: "forward_fill"
  provider: auto  # Primary data provider: 'polygon', 'databento', or 'auto'
  fallback_provider: databento  # Fallback data provider for reliability
  polygon_timeout: 30  # Request timeout in seconds
  polygon:
    api_key: ${POLYGON_API_KEY}
    base_url: https://api.polygon.io
    api_version: v2
    rate_limit:
      calls_per_minute: 5
      burst_limit: 10
    retry:
      attempts: 3
      backoff_factor: 2.0
    cache:
      directory: data/cache/polygon
      format: parquet
      partition_format: "year=%Y/month=%m/day=%d"
    validation:
      enabled: true
      fill_gaps: forward_fill
      outlier_detection: true
  databento:
    api_key: ${DATABENTO_API_KEY}

features:
  data_source: 'polygon'
  technical:
    calculate_returns: true
    calculate_log_returns: true
    sma_windows: [5, 10, 20, 50]
    ema_windows: [5, 10, 20, 50]
    calculate_atr: true
    atr_window: 10
    calculate_rsi: true
    rsi_window: 14
    calculate_macd: true
    calculate_bollinger_bands: true
    bollinger_window: 20
    calculate_stochastic: true
    calculate_williams_r: true
    # Additional intraday/VPA-style knobs
    rvol_window: 390
    vol_of_vol: { enabled: true, window: 14, vol_window: 14 }
    sma_slope: { enabled: true, window: 20, slope_window: 5 }
    obv: { enabled: true }
  microstructure:
    calculate_spread: true
    calculate_microprice: true
    calculate_queue_imbalance: true
    calculate_vwap: true
    calculate_twap: true
    calculate_price_impact: true
    fvg: { enabled: true }
  time:
    extract_time_of_day: true
    extract_day_of_week: true
    extract_session_features: true
  vix:
    enabled: true
    path: data/external/vix.parquet
    term_structure: false
  # New feature groups
  vpa:
    enabled: true
    climax_rvol_threshold: 3.0
    zscore_window: 100
    persistence_window: 10
    direction_ema_span: 10
  ict:
    enabled: true
    opening_range_minutes: 15
    displacement_k_atr: 1.5
  volatility:
    enabled: true
  smt:
    enabled: true
    momentum_span: 5
    paths:
      SPY: data/raw/SPY_1min.parquet
      QQQ: data/raw/QQQ_1min.parquet
  polygon:
    features:
      use_vwap_column: true
    quality_checks:
      enabled: true

regime:
  vix: true
  cvol: true
  macro_flags: true

execution:
  tick_value: 0.01            # SPY tick $0.01 (1 cent per share)
  point_value: 1.0            # $ per point for SPY ETF
  spread_ticks: 1             # baseline spread consumption
  impact_bps: 0.5             # temporary impact per 1% ADV (toy)
  commission_per_contract: 0.0035  # Typical ETF commission per share

risk:
  risk_per_trade_frac: 0.02   # 2%
  stop_r_multiple: 1.0
  tp_r_multiple: 1.5
  max_daily_loss_r: 3.0       # kill-switch
  max_position_size: 1000
  max_leverage: 0.05

env:
  step_seconds: 60
  reward:
    kind: "blend"             # blend of DSR and raw pnl with penalties
    dd_penalty: 0.1
    eod_inventory_penalty: 0.5
    alpha: 0.5   # DSR weight
    beta: 0.5    # raw pnl weight
    micro_penalty: 0.001
  trading:
    no_trade_open_minutes: 5
    no_trade_close_minutes: 5
    widen_spread_minutes: 15

train:
  algo: "ppo_lstm"
  total_steps: 300000
  batch_size: 1024
  learning_rate: 1.0e-4
  n_envs: 8
  gamma: 0.995
  gae_lambda: 0.97
  clip_range: 0.2
  vf_coef: 0.5
  ent_coef: 0.005
  n_steps: 1024
  target_kl: 0.03
  lr_schedule: cosine   # none|linear|cosine
  ent_anneal_final: 0.003
  policy_kwargs:
    lstm_hidden_size: 128
    net_arch_pi: [128, 64]
    net_arch_vf: [128, 64]
  torch_threads: 1
  device: cpu
  # Feature selection and pruning
  feature_selection:
    correlation_threshold: 0.95
    min_variance: 1.0e-10

walkforward:
  train_days: 30
  test_days: 10
  embargo_minutes: 60

logging:
  level: INFO
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: logs/trading_system.log
  max_bytes: 10485760  # 10MB
  backup_count: 5

monitoring:
  enable_prometheus: false
  prometheus_port: 8000
  metrics_interval: 60  # seconds
  alert_file: alerts/alerts.yaml
