project: rl-intraday
seed: 42

data:
  instrument: MES
  minute_file: data/raw/mes_1min.parquet        # Databento/IBKR backfill
  vix_file: data/external/vix.csv
  cvol_file: data/external/cvol.csv
  macro_flags_file: data/external/macro_flags.csv
  session:
    tz: America/New_York
    rth_start: "09:30"
    rth_end: "16:00"
  lookback_bars: 120            # ~2 hours context for LSTM
  resample: "1min"
  drop_na_policy: "forward_fill"

features:
  returns_horizons: [1, 5, 15]
  technical:
    returns_horizons: [1,3,5,15,60]
    atr_window: 14
    range_vol_windows: [30,60,90]
  microstructure:
    enable: true
    ofi_levels: 1
    microprice: true
    spread_regime: true
  seasonality:
    tod_encoding: true
  regimes:
    vix: true
    macro_flags: true

regime:
  vix: true
  cvol: true
  macro_flags: true

execution:
  tick_value: 1.25            # MES tick $1.25 (0.25 index pt * $5)
  point_value: 5.0            # $ per index point for MES
  spread_ticks: 1             # baseline spread consumption
  impact_bps: 0.5             # temporary impact per 1% ADV (toy)
  commission_per_contract: 0.6

risk:
  risk_per_trade_frac: 0.02   # 2%
  stop_r_multiple: 1.0
  tp_r_multiple: 1.5
  max_daily_loss_r: 3.0       # kill-switch

env:
  step_seconds: 60
  reward:
    kind: "dsr"               # differential sharpe
    dd_penalty: 0.1
    eod_inventory_penalty: 0.5

train:
  algo: "ppo_lstm"
  total_steps: 1_200_000
  batch_size: 8192
  learning_rate: 3.0e-4
  n_envs: 1
  gamma: 0.99
  gae_lambda: 0.95
  clip_range: 0.2
  vf_coef: 0.5
  ent_coef: 0.0
  n_steps: 2048
  policy_kwargs:
    lstm_hidden_size: 128
    net_arch_pi: [128, 64]
    net_arch_vf: [128, 64]

walkforward:
  train_days: 30
  test_days: 10
  embargo_minutes: 60

logging:
  level: INFO
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: logs/trading_system.log
  max_bytes: 10485760  # 10MB
  backup_count: 5

monitoring:
  enable_prometheus: false
  prometheus_port: 8000
  metrics_interval: 60  # seconds
  alert_file: alerts/alerts.yaml

"""
Sample configuration illustrating additions for cross‑asset features and risk management.

This YAML file extends the original ``configs/settings.yaml`` with new keys for
external data files and returns horizons.  You can merge these entries into
your existing configuration.  Replace paths (``data/vix.csv``, etc.) with the
actual locations of your downloaded datasets.
"""

data:
  # Path to historical minute/tick data provided by Databento
  databento_api_key: db-PyiEQuyM4SxeyVyLMVJBfPfnsqgcN
  instruments:
    - MES
  # Cross‑asset data files
  vix_file: data/vix.csv        # CSV with columns: date, vix
  cvol_file: data/cvol.csv      # CSV with columns: date, cvol_equity, cvol_bond, ...
  macro_flags_file: data/macro_flags.csv  # CSV with columns: date, nfp_flag, cpi_flag, fomc_flag, ...

features:
  returns_horizons: [1, 5, 15]  # compute 1‑minute, 5‑minute and 15‑minute percentage returns
  # other feature settings (SMA, ATR, RSI etc.) remain unchanged

regime:
  vix: true          # enable VIX feature
  cvol: true         # enable CVOL feature
  macro_flags: true  # enable macro event flags

risk:
  risk_per_trade_frac: 0.02   # 2% of account risk per trade
  stop_r_multiple: 1.0        # stop loss at 1R
  tp_r_multiple: 1.5          # take profit at 1.5R (triple‑barrier exit ratio)
  max_daily_loss_r: 3.0       # daily kill‑switch triggers at 3R drawdown

train:
  # RL algorithm settings (PPO‑LSTM as baseline).  Replace with distributional DQN if implemented.
  algorithm: ppo_lstm
  n_envs: 1
  total_timesteps: 500000